services:
  - type: web
    name: ai-resume-screener-backend
    env: python
    region: ohio # Change as needed
    plan: free
    repo: https://github.com/Lightrox/AI-Resume_Screener # Update this!
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker backend.app.main:app"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
